config/routes.rb
Mastery::Application.routes.draw do

  devise_for :users

  resources :users, only: [ :index ]
  resources :users, path: '/', only: [ :show, :destroy ]
  resources :activities, path: ':username/activities' do
    resources :instances, only: [ :show, :update, :destroy ]
    match 'start', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Timed' }
    match 'tally', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Counted' }
    match 'stop', to: 'activities#stop', via: [ :get, :post ]
    match ':activity_id/stop', to: 'instances#stop', via: [ :get, :post ]
  end
  root to: 'static_pages#home'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :activity
  validates :type, presence: true, inclusion: { in: Activity::TYPES }
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_action :set_instance, only: [:show, :update, :destroy]
  before_action :set_activity

  # GET /instances/1
  # GET /instances/1.json
  def show
  end

  # GET/POST /instances/1/stop
  def stop
    respond_to do |format|
      if @instance.stop
        format.html { redirect_to activity_path(@user,@activity), notice: 'Activity was successfully stopped.'}
        format.json { render action: 'show', status: :accepted, location: activity_path(@user,@activity) }
      else
        format.html { redirect_to activity_path(@user,@activity), error: @instance.errors }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = @activity.instances.new(instance_params)
    Rails.logger.info @instance.attributes

    respond_to do |format|
      if @instance.save
        format.html { redirect_to activity_path(@user,@activity), notice: "Activity was successfully #{@instance.type == 'Timed' ? 'begun' : 'tallied'}." }
        format.json { render action: 'show', status: :created, location: activity_path(@user,@activity) }
      else
        format.html { redirect_to activity_path(@user,@activity), error: @instance.errors }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instances/1
  # PATCH/PUT /instances/1.json
  def update
    respond_to do |format|
      if @instance.update(instance_params)
        format.html { redirect_to activity_path(@user,@activity), notice: 'Activity log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance.destroy
    respond_to do |format|
      format.html { redirect_to activity_path(@user,@activity) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instance
      @instance = Instance.find(params[:id])
    end
    def set_activity
      @activity = Activity.find(params[:activity_id])
      @user = @activity.user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instance_params
      params[:instance].permit(:type,:started,:done,:private)
    end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_counted_list.html.haml
%ul.list-group
  - if @activity.counteds.empty?
    %li.list-group-item
      There are no counts of #{@activity.name} yet.
      = link_to 'Create one?', activity_tally_path(@user, @activity)
  - @activity.counteds.order('started DESC, done DESC').each do |i|
    %li.list-group-item.clearfix{ title: i.done.strftime("%Y.%m.%d %R") }
      .col-md-8
        %h4
          - if i.done > Time.now - 1.week
            = distance_of_time_in_words_to_now(i.done)
            = i.done < Time.now ? 'ago' : 'from now'
          - else
            on
            - if i.done.year == Time.now.year
              = i.done.strftime("%B %-d at %-I:%M:%S%p")
            - else
              = i.done.strftime("%B %-d, %Y, at %-I:%M:%S%p")
      .col-md-4
        .btn-group.btn-group-justified
          = link_to 'Delete', activity_instance_path(@user,@activity,i), method: :delete, data: {confirm: 'Are you sure you wish to delete this instance?'}, class: 'btn btn-danger', type: 'button'
- if @activity.stopped?
  .panel-footer.btn-group.btn-group-justified
    = link_to 'Count', activity_tally_path(@user,@activity), class: 'btn btn-primary'

app/views/instances/_form.html.haml
= form_for @instance do |f|
  - if @instance.errors.any?
    #error_explanation
      %h2= "#{pluralize(@instance.errors.count, "error")} prohibited this instance from being saved:"
      %ul
        - @instance.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/instances/_timed_list.html.haml
%ul.activity-listing
  - if @activity.timeds.empty?
    %li
      %h3 There are no instances of #{@activity.name} yet.
  - @activity.timeds.order('started DESC, done DESC').each do |i|
    %li{ title: i.started.strftime("%Y.%m.%d %R") + (i.done? ? " (#{i.time_spent})" : " – ongoing"), class: i.done? ? '' : 'active' }
      %h3
        - if i.started > Time.now - 1.week
          = distance_of_time_in_words_to_now(i.started,true).capitalize
          = i.started < Time.now ? 'ago' : 'from now'
        - else
          on
          - if i.started.year == Time.now.year
            = i.started.strftime("%B %-d at %-I:%M:%S%p")
          - else
            = i.started.strftime("%B %-d, %Y, at %-I:%M:%S%p")
        - if i.done?
          %small
            For
            = distance_of_time_in_words(i.done,i.started,true)
        - else
          %small{ data: { timer: true, since: i.started.to_i * 1000 }}
            = i.time_spent
      - if !i.done?
        = link_to activity_stop_path(@user,@activity), class: 'button small right', type: 'button', title: 'Stop', data: { tooltip: true } do
          %i.fi-stop
      - else
        = link_to activity_instance_path(@user,@activity,i), method: :delete, data: {confirm: 'Are you sure you wish to delete this instance?', tooltip: true}, class: 'button small alert right', type: 'button', title: 'Delete' do
          %i.fi-trash
  - if @activity.stopped?
    %li
      = link_to activity_start_path(@user,@activity), class: 'large button expand' do
        %i.fi-play
        Start

app/views/instances/edit.html.haml
%h1 Editing instance

= render 'form'

= link_to 'Show', @instance
\|
= link_to 'Back', instances_path

app/views/instances/index.html.haml
%h1 Listing instances

%table
  %tr
    %th
    %th
    %th

  - @instances.each do |instance|
    %tr
      %td= link_to 'Show', instance
      %td= link_to 'Edit', edit_instance_path(instance)
      %td= link_to 'Destroy', instance, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Instance', new_instance_path

app/views/instances/new.html.haml
%h1 New instance

= render 'form'

= link_to 'Back', instances_path

app/views/instances/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_instance_path(@instance)
\|
= link_to 'Back', instances_path