config/routes.rb
Mastery::Application.routes.draw do

  devise_for :users

  resources :users, only: [ :index ]
  resources :users, path: '/', only: [ :show, :destroy ]
  resources :activities, path: ':username/activities' do
    resources :instances, only: [ :show, :update, :destroy ]
    match 'start', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Timed' }
    match 'tally', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Counted' }
    match 'stop', to: 'activities#stop', via: [ :get, :post ]
    match ':activity_id/stop', to: 'instances#stop', via: [ :get, :post ]
  end
  root to: 'static_pages#home'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  self.inheritance_column = nil
  belongs_to :user
  has_many :instances
  has_many :timeds
  has_many :counteds

  TYPES = [ 'Timed', 'Counted' ]
  validates :name, :type, presence: true
  validates :name, length: { minimum: 3 }
  validates :type, inclusion: { in: TYPES }
  validates_associated :user

  def running?
    !timeds.where(done: nil).empty?
  end

  def stopped?
    !running?
  end

  def stop
    timeds.stop
  end

  def total_count
    counteds.length
  end

  def self.timed
    where( type: 'Timed' )
  end

  def self.counted
    where( type: 'Counted' )
  end

  def time_spent(format = '%d, %H and %N')
    sum = 0
    timeds.each do |i|
      sum += (i.done || Time.now) - i.started
    end
    Time.diff(Time.now - sum,Time.now,format)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:stop, :show, :edit, :update, :destroy]
  before_action :set_user
  before_filter :authenticate_user!
  layout 'jumbotron', only: [:show]

  # GET /user/:user_id/activities
  # GET /user/:user_id/activities.json
  def index
    @activities = @user.activities.all
  end

  # GET /user/:user_id/activities/1
  # GET /user/:user_id/activities/1.json
  def show

  end

  # GET /user/:user_id/activities/new
  def new
    @activity = Activity.new
    @activity[:type] ||= params[:type]
  end

  # GET /user/:user_id/activities/1/edit
  def edit
  end

  # POST /user/:user_id/activities
  # POST /user/:user_id/activities.json
  def create
    @activity = @user.activities.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to activity_url(@user,@activity), notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT/GET /user/:user_id/activities/1/stop
  def stop
    respond_to do |format|
      if @activity.stop
        format.html { redirect_to activity_url(@user,@activity), notice: 'Activity was successfully stopped.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user/:user_id/activities/1
  # PATCH/PUT /user/:user_id/activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@user,@activity), notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user/:user_id/activities/1
  # DELETE /user/:user_id/activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id] || params[:activity_id])
    end

    def set_user
      @user = User.find_by(username: params[:username])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :type, :private, :user_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity, url: @activity.new_record? ? activities_path : activity_path(@activity.user,@activity), html: { class: 'medium-8 medium-centered columns', role: 'form' } do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  = f.label :name, class: 'sr-only'
  = f.text_field :name, placeholder: 'Name', class: 'form-control'
  = f.label :type, class: 'sr-only'
  = f.select :type, options_for_select(Activity::TYPES.map{|x| [x.titleize,x]}, @activity[:type]), {}, class: 'form-control'
  = f.check_box :private
  = f.label :private, class: 'form-control'
  .row
    .small-12.columns.actions.text-right
      = f.submit 'Save', class: 'button'
      - if !@activity.new_record?
        = link_to 'Show', activity_path(@activity.user,@activity), class: 'btn btn-default'

app/views/activities/edit.html.haml
- content_for :title, 'Editing Activity'

= render 'form'

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th Name
    %th Type
    %th Private
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= activity.name
      %td= activity.type.titleize
      %td= activity.private
      %td= link_to 'Show', activity_path(activity.user,activity)
      %td= link_to 'Edit', edit_activity_path(activity.user, activity)
      %td= link_to 'Destroy', activity_path(activity.user,activity), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
- content_for :title, 'New Activity'

= render 'form'

app/views/activities/show.html.haml
- content_for :jumbotron do
  %h1
    = @activity.name.titleize
    %br
    %small
      = @activity.private? ? "Private" : "Public"
      = @activity.type.titleize
      Activity
      = surround '(',')' do
        =link_to '@'+@user.username, @user

.row
  .medium-4.columns
    - if @activity.type.downcase=='timed'
      %h3.time-spent{data: { 'diff-format' => '%H'}}
        = @activity.time_spent('%H')[:diff]
        %br
        %small.time-spent
          = surround '(',')' do
            = @activity.time_spent[:diff]
    - else
      %h4.tally
        = pluralize(@activity.counteds.length,'time')
    .button-group
      -# TODO: SET UP GOALS ARCHITECTURE
      = link_to '#', class: 'button secondary', title: 'Coming Soon', data: { tooltip: true } do
        %i.fi-graph-bar
        Set Goals
      = link_to edit_activity_path(@activity.user,@activity), class: 'button' do
        %i.fi-pencil
        Edit
  %section.medium-8.columns
    %h2 Recent activity
    = render "instances/#{@activity.type.downcase}_list", locals: { activity: @activity }