config/routes.rb
Mastery::Application.routes.draw do

  devise_for :users

  resources :users, only: [ :index ]
  resources :users, path: '/', only: [ :show, :destroy ]
  resources :activities, path: ':username/activities' do
    resources :instances, only: [ :show, :update, :destroy ]
    match 'start', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Timed' }
    match 'tally', to: 'instances#create', via: [ :get, :post ], instance: { type: 'Counted' }
    match 'stop', to: 'activities#stop', via: [ :get, :post ]
    match ':activity_id/stop', to: 'instances#stop', via: [ :get, :post ]
  end
  root to: 'static_pages#home'

end

app/views/layouts/_head.haml
%head
  %meta{ name: 'viewport', content: 'initial-scale=1, maximum-scale=1' }
  %title<
    Mastery
    - if content_for? :title
      |
      =content_for(:title)
  = stylesheet_link_tag '//fonts.googleapis.com/css?family=IM+Fell+French+Canon:400,400italic'
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'modernizr'
  = csrf_meta_tags
  / [if lt IE 9]
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    -# <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

app/views/layouts/_navigation.haml
.contain-to-grid.sticky
  %nav.top-bar{ role: 'navigation', data: { topbar: true } }
    %ul.title-area
      %li.name
        %h1
          =link_to root_path, class: 'navbar-brand' do
            mastery
            - if user_signed_in?
              %i.fi-home
      %li.toggle-topbar.menu-icon
        %a
          %span
    %section.top-bar-section
      %ul.right
        - if user_signed_in?
          %li.has-dropdown
            = link_to '#', class: 'dropdown-toggle', title: 'New Activity', data: { toggle: 'dropdown' } do
              %i.fi-plus
              New Activity
            %ul.dropdown{ role: 'menu' }
              %li
                = link_to new_activity_path(current_user, { type: 'timed' }) do
                  %i.fi-clock
                  Timed
              %li
                = link_to new_activity_path(current_user, { type: 'counted' }) do
                  %i.fi-check
                  Counted
          %li.has-dropdown
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' }, title: 'Track Activity' do
              %i.fi-list
              Track Activity
            %ul.dropdown{ role: 'menu' }
              - if current_user.activities.length > 0
                %li
                  %label
                    %i.fi-clock
                    Timed Activities
                - if current_user.activities.timed.length > 0
                  - current_user.activities.timed.each do |activity|
                    %li
                      = link_to activity_path(activity.user,activity) do
                        =activity.name
                - else
                  %li
                    = link_to new_activity_path(current_user) do
                      Create timed Activity
                %li.divider
                %li
                  %label
                    %i.fi-check
                    Counted Activities
                - if current_user.activities.counted.length > 0
                  - current_user.activities.counted.each do |activity|
                    %li
                      = link_to activity_path(activity.user,activity) do
                        =activity.name
                - else
                  %li
                    = link_to new_activity_path(current_user) do
                      Create counted Activity

              - else
                %li
                  %label You do not have any Activities yet.
                %li
                  = link_to new_activity_path(current_user) do
                    %i.fi-plus
                    Create one
          %li
            =link_to edit_user_registration_path, title: 'Edit Account' do
              %i.fi-wrench
              ="@#{current_user.username}"
          %li
            =link_to destroy_user_session_path, method: 'delete' do
              %i.fi-power
              Sign Out
        - else
          %li.has-dropdown
            = link_to 'Login', '#', data: { dropdown: 'signin' }
          %li= link_to 'Sign Up', new_user_registration_path
- if !user_signed_in?
  #signin.f-dropdown.small.content{ data: { 'dropdown-content' => true }}
    = form_tag user_session_path, html: { role: 'form' } do
      .row.collapse
        .small-2.columns
          %span.prefix.radius @
        .small-10.columns
          = text_field_tag 'user[username]', '', placeholder: 'Username', class: 'form-control', size: 35
      .row.collapse
        .small-12.columns
          = password_field_tag 'user[password]', '', placeholder: 'Password', class: 'form-control'
      .row.collapse
        %label.checkbox.small-6.columns
          = check_box_tag 'user[remember_me]'
          Remember Me
        .small-6.columns
          %button.button.primary.right Sign in
    %p.right= link_to 'Forgot your password?', new_password_path('user')

app/views/layouts/_notifications.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .row
      .alert-box{class: (name == :notice ? "success" : "warning"), data: { alert: true}}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.haml
!!!
%html
  = render 'layouts/head'
  %body.base{ class: body_classes }
    .off-canvas-wrap
      .inner-wrap
        =render 'layouts/navigation'
        %main{ role: 'main' }
          .row
            %header.small-12.columns
              = content_tag(:h1, content_for(:title))    if content_for? :title
              = content_tag(:h4, content_for(:subtitle)) if content_for? :subtitle
          - if !flash.empty?
            .row
              .small-12.columns=render 'layouts/notifications'
          .row
            .small-12.columns
              = yield
        %footer
          .row
            %p Copyright ©2013 Ben Saufley
    = javascript_include_tag 'application'

app/views/layouts/jumbotron.haml
!!!
%html
  = render 'layouts/head'
  %body.jt{ class: body_classes }
    .off-canvas-wrap
      .inner-wrap
        =render 'layouts/navigation'
        %header.jumbotron
          .row
            .small-12.medium-6.columns
              = content_for :jumbotron
        %main{ role: 'main' }
          - if !flash.empty?
            .row
              .small-12.columns=render 'layouts/notifications'
          = yield
        %footer
          .row
            %p.center
              %small Copyright ©2013 Ben Saufley
    = javascript_include_tag 'application'

app/views/layouts/static.haml
!!!
%html
  %head
    %meta{ name: 'viewport', content: 'initial-scale=1, maximum-scale=1' }
    %title Mastery
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
    / [if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      -# <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  %body.static
    =render 'layouts/navigation'
    - if content_for?(:jumbotron) || content_for?(:title)
      %header.jumbotron
        .container
          = content_for(:jumbotron) if content_for? :jumbotron
          - if !user_signed_in?
            .row
              .col-sm-4.col-sm-offset-4
                = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-primary btn-block'
    %main{ role: 'main' }
      .container
        %header
          - if !content_for?(:right) && !flash.empty?
            =render 'layouts/notifications'
        %section= yield
    %footer
      .container
        %p Copyright ©2013 Ben Saufley
    = javascript_include_tag "application"